#!/usr/bin/env node
// The index /quality/gates prints: which commit last wrote each check.
//
//   npm run gates:index
//
// The page reads the check names and their assertions straight out of the two
// harness scripts at render time, so nothing about a check is typed twice. The
// one thing a script cannot tell you about itself is when it was written, and
// that is what this writes: `git blame` for the lines carrying `ok(…)`, mapped
// through the commit log to a short hash, a date and a subject.
//
// Keyed by `suite|name` rather than by line number, so adding a check above
// another one does not rewrite the file — only a check whose own line was
// rewritten gets a new commit. `npm run check:exports` regenerates this in
// memory and fails when the checked-in copy is stale, which is the only way a
// generated file stays true.

import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { HARNESSES, parseGateCalls } from "../src/lib/gates.ts";

const OUT = "src/lib/gates-added.json";
const ROOT = process.cwd();

function git(args: string[]): string {
  return execFileSync("git", args, { cwd: ROOT, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
}

/** The repository's own commits, hashed to a subject and a date. */
function commitLog(): Map<string, { c: string; s: string; d: string }> {
  const map = new Map();
  const out = git(["log", "--format=%H%x1f%h%x1f%ad%x1f%s", "--date=short"]);
  for (const line of out.split("\n")) {
    if (!line.trim()) continue;
    const [full, short, date, subject] = line.split("\x1f");
    map.set(full, { c: short, s: subject ?? "", d: date ?? "" });
  }
  return map;
}

/** Line number → full commit hash, from one blame run per file. */
function blameLines(file: string): Map<number, string> {
  const out = git(["blame", "--line-porcelain", "--", file]);
  const map = new Map<number, string>();
  let hash = "";
  for (const line of out.split("\n")) {
    const header = /^([0-9a-f]{40}) \d+ (\d+)(?: \d+)?$/.exec(line);
    if (header) {
      hash = header[1];
      map.set(Number(header[2]), hash);
    }
  }
  return map;
}

/** The index, as both this script and check:exports compute it. */
export function buildIndex(): { generatedFrom: string; note: string; checks: Record<string, { c: string; s: string; d: string }> } {
  const commits = commitLog();
  const checks: Record<string, { c: string; s: string; d: string }> = {};
  for (const h of HARNESSES) {
    const source = fs.readFileSync(path.join(ROOT, h.file), "utf8");
    const blame = blameLines(h.file);
    for (const call of parseGateCalls(h.file, h.suite, source)) {
      const key = `${h.suite}|${call.name}`;
      if (checks[key]) continue;
      const hash = blame.get(call.line);
      const commit = hash ? commits.get(hash) : undefined;
      if (commit) checks[key] = commit;
    }
  }
  const sorted = Object.fromEntries(Object.keys(checks).sort().map((k) => [k, checks[k]]));
  return {
    generatedFrom: "git blame over the ok(…) calls in scripts/check-exports.mjs and scripts/check-demos.mjs",
    note: "Generated by `npm run gates:index`; check:exports fails when this file no longer matches the scripts. The commit is the one that last wrote the check's line, which is the batch that added it unless the line was edited later.",
    checks: sorted,
  };
}

if (process.argv[1]?.endsWith("gen-gates-index.mts")) {
  const index = buildIndex();
  fs.writeFileSync(path.join(ROOT, OUT), JSON.stringify(index, null, 2) + "\n");
  console.log(`gates:index — ${Object.keys(index.checks).length} checks → ${OUT}`);
}
